SELECT * FROM TABELA_DE_CLIENTES;

SELECT TOP 4 * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';

SELECT DISTINCT TOP 5 SABOR FROM TABELA_DE_PRODUTOS;

--INICIO DESAFIO

SELECT * FROM NOTAS_FISCAIS;

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';

--FIM DESAFIO