SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES --> 7 CLIENTES POSSUEM NO SEUS BAIRROS VENDEDORES

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES --> 3 VENDEDORES POSSUEM NO SEUS BAIRROS CLIENTES

SELECT TV.NOME AS NOME_DO_VENDEDOR, TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
INNER JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO


--QUAL É O VENDEDOR QUE NÃO TEM CLIENTE NO SEU BAIRRO ?

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
RIGHT JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.BAIRRO IS NULL;
--R: Roberta Martins - Copacabana


--QUAIS SÃO OS CLIENTES QUE NÃO TEM VENDEDORES NO SEU BAIRRO ?

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL;
--R:
--Fernando Cavalcante
--Juliana Silva
--Marcos Nogueira
--Abel Silva 
--Petra Oliveira
--Marcelo Mattos
--Edson Meilelles
--Walber Lontra
--Fabio Carvalho


SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
FULL JOIN TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO;