SELECT GETDATE()

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS,
DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS,
DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS, 
DATEDIFF(DAY, '2024-01-01', GETDATE()) AS DIAS_DESDE_INICIO_ANO

SELECT GETDATE() AS DATA_HOJE, DATEPART(DAY, GETDATE()) AS DIA_DE_HOJE

SELECT ISDATE(DATETIMEFROMPARTS(2024, 02, 03, 00, 00, 00, 00))


--INICIO DESAFIO


SELECT * FROM TABELA_DE_CLIENTES;

SELECT DATENAME(DAY, '2023-01-10')

SELECT CONCAT(NOME, ' nasceu em ',
DATENAME(WEEKDAY, DATA_DE_NASCIMENTO), ',',
DATENAME(DAY, DATA_DE_NASCIMENTO), ' de ',
DATENAME(MONTH, DATA_DE_NASCIMENTO), ' de ',
DATENAME(YEAR, DATA_DE_NASCIMENTO)) AS DATA_EXTENSO FROM TABELA_DE_CLIENTES


--FIM DESAFIO