CREATE DATABASE SUCOS_VENDAS;

CREATE TABLE [TABELA DE CLIENTES](

[CPF] [VARCHAR] (11),
[NOME] [VARCHAR] (100),
[RUA] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]

);

CREATE TABLE [TESTE](
[CPF] [CHAR] (3)
);

CREATE TABLE [TABELA DE PRODUTOS](

[CODIGO DO PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
[NOME DO PRODUTO] [VARCHAR] (150),
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO DE LISTA] [SMALLMONEY] 

);

DROP TABLE [TESTE] --DELETA A TABELA TESTE

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL; --ALTERA A TABELA E A COLUNA
PRIMARY KEY CLUSTERED ([CPF]);