SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES];


SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES];


SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES]
ORDER BY [NOME];


SELECT [ESTADO], [NOME] FROM [TABELA DE CLIENTES];

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA] FROM [TABELA DE PRODUTOS];


SELECT [NOME], [CPF], [ESTADO]
FROM [TABELA DE CLIENTES]


SELECT [NOME] AS [NOME DO CLIENTE], [CPF], [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES]

--INICIO DESAFIO

SELECT [MATRICULA] AS [IDENTIFICADOR], [NOME] AS [NOME DO VENDEDOR]
FROM [TABELA DE VENDEDORES]

--FIM DESAFIO

SELECT [SABOR] FROM [TABELA DE PRODUTOS];

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];
